//
//  AppGroupShared.h
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// 应用组共享容器工具类
@interface AppGroupShared : NSObject

// 设置扩展的应用组ID
@property (class, nonatomic, strong, readonly) NSString *appGroupID;

// 应用组共享容器的文件系统目录URL
@property (class, nonatomic, strong, readonly) NSURL *appGroupSharedContainerDirectory;

// 应用组共享的UserDefaults
@property (class, nonatomic, strong, readonly) NSUserDefaults *appGroupSharedDefaults;

@end

NS_ASSUME_NONNULL_END
