//
//  AppGroupShared.m
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import "AppGroupShared.h"

@implementation AppGroupShared

static NSString *_appGroupID = nil;
static NSURL *_appGroupSharedContainerDirectory = nil;
static NSUserDefaults *_appGroupSharedDefaults = nil;

+ (NSString *)appGroupID {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _appGroupID = @"group.com.tiqmo.wallet.ksa.uat.appleExtensionUAT";
    });
    return _appGroupID;
}

+ (NSURL *)appGroupSharedContainerDirectory {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _appGroupSharedContainerDirectory = [[NSFileManager defaultManager] containerURLForSecurityApplicationGroupIdentifier:self.appGroupID];
        if (!_appGroupSharedContainerDirectory) {
            NSLog(@"Failed to get app group container directory");
        }
    });
    return _appGroupSharedContainerDirectory;
}

+ (NSUserDefaults *)appGroupSharedDefaults {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _appGroupSharedDefaults = [[NSUserDefaults alloc] initWithSuiteName:self.appGroupID];
        if (!_appGroupSharedDefaults) {
            NSLog(@"Failed to initialize app group shared defaults");
            _appGroupSharedDefaults = [NSUserDefaults standardUserDefaults];
        }
    });
    return _appGroupSharedDefaults;
}

@end
