//
//  EncryptedPassDataResponse.m
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import "EncryptedPassDataResponse.h"

@implementation EncryptedPassDataResponse

- (instancetype)initWithActivationData:(nullable NSData *)activationData
                     encryptedPassData:(nullable NSData *)encryptedPassData
                    ephemeralPublicKey:(nullable NSData *)ephemeralPublicKey
                           wrappedKey:(nullable NSData *)wrappedKey {
    self = [super init];
    if (self) {
        _activationData = [activationData copy];
        _encryptedPassData = [encryptedPassData copy];
        _ephemeralPublicKey = [ephemeralPublicKey copy];
        _wrappedKey = [wrappedKey copy];
    }
    return self;
}

@end
