//
//  EncryptedPassDataResponse.h
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// 模拟加密通行证数据响应对象
@interface EncryptedPassDataResponse : NSObject

@property (nonatomic, strong, nullable) NSData *activationData;
@property (nonatomic, strong, nullable) NSData *encryptedPassData;
@property (nonatomic, strong, nullable) NSData *ephemeralPublicKey;
@property (nonatomic, strong, nullable) NSData *wrappedKey;

- (instancetype)initWithActivationData:(nullable NSData *)activationData
                     encryptedPassData:(nullable NSData *)encryptedPassData
                    ephemeralPublicKey:(nullable NSData *)ephemeralPublicKey
                           wrappedKey:(nullable NSData *)wrappedKey;

@end

NS_ASSUME_NONNULL_END
