//
//  PassResource.m
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import "PassResource.h"

@implementation PassResource

+ (EncryptedPassDataResponse *)requestPaymentPassDataWithConfiguration:(PKAddPaymentPassRequestConfiguration *)configuration
                                                     certificateChain:(NSArray<NSData *> *)certificates
                                                                 nonce:(NSData *)nonce
                                                        nonceSignature:(NSData *)nonceSignature {
    
    EncryptedPassDataResponse *response = [[EncryptedPassDataResponse alloc] init];
    response.activationData = [[NSData alloc] init];
    response.encryptedPassData = [[NSData alloc] init];
    
    if (configuration.encryptionScheme == PKEncryptionSchemeECC_V2) {
        response.ephemeralPublicKey = [[NSData alloc] init];
    } else if (configuration.encryptionScheme == PKEncryptionSchemeRSA_V2) {
        response.wrappedKey = [[NSData alloc] init];
    }
    
    return response;
}

@end
