//
//  PassResource.h
//  IssuerApp
//
//  Created by Generated by Makr on 2026
//

#import <Foundation/Foundation.h>
#import <PassKit/PassKit.h>
#import "EncryptedPassDataResponse.h"

NS_ASSUME_NONNULL_BEGIN

// 模拟检索支付通行证所需数据的结构
@interface PassResource : NSObject

+ (EncryptedPassDataResponse *)requestPaymentPassDataWithConfiguration:(PKAddPaymentPassRequestConfiguration *)configuration
                                                     certificateChain:(NSArray<NSData *> *)certificates
                                                                 nonce:(NSData *)nonce
                                                        nonceSignature:(NSData *)nonceSignature;

@end

NS_ASSUME_NONNULL_END
