//
//  ProvisioningCredential.h
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

// 模拟用户默认数据库中存储的数据结构，用于支持非UI扩展中的代码
@interface ProvisioningCredential : NSObject <NSSecureCoding, NSCopying>

@property (nonatomic, copy) NSString *primaryAccountIdentifier;
@property (nonatomic, copy) NSString *label;
@property (nonatomic, copy) NSString *assetName;
@property (nonatomic, assign) BOOL isAvailableForProvisioning;
@property (nonatomic, copy) NSString *cardholderName;
@property (nonatomic, copy) NSString *localizedDescription;
@property (nonatomic, copy) NSString *primaryAccountSuffix;
@property (nonatomic, copy) NSString *expiration;

- (instancetype)initWithPrimaryAccountIdentifier:(NSString *)primaryAccountIdentifier
                                           label:(NSString *)label
                                       assetName:(NSString *)assetName
                        isAvailableForProvisioning:(BOOL)isAvailableForProvisioning
                                 cardholderName:(NSString *)cardholderName
                           localizedDescription:(NSString *)localizedDescription
                            primaryAccountSuffix:(NSString *)primaryAccountSuffix
                                     expiration:(NSString *)expiration;

// 从字典初始化
- (instancetype)initWithDictionary:(NSDictionary *)dictionary;

// 转换为字典
- (NSDictionary *)toDictionary;

@end

NS_ASSUME_NONNULL_END
