//
//  ProvisioningCredential.m
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import "ProvisioningCredential.h"

@implementation ProvisioningCredential

+ (BOOL)supportsSecureCoding {
    return YES;
}

- (instancetype)initWithPrimaryAccountIdentifier:(NSString *)primaryAccountIdentifier
                                           label:(NSString *)label
                                       assetName:(NSString *)assetName
                        isAvailableForProvisioning:(BOOL)isAvailableForProvisioning
                                 cardholderName:(NSString *)cardholderName
                           localizedDescription:(NSString *)localizedDescription
                            primaryAccountSuffix:(NSString *)primaryAccountSuffix
                                     expiration:(NSString *)expiration {
    self = [super init];
    if (self) {
        _primaryAccountIdentifier = [primaryAccountIdentifier copy];
        _label = [label copy];
        _assetName = [assetName copy];
        _isAvailableForProvisioning = isAvailableForProvisioning;
        _cardholderName = [cardholderName copy];
        _localizedDescription = [localizedDescription copy];
        _primaryAccountSuffix = [primaryAccountSuffix copy];
        _expiration = [expiration copy];
    }
    return self;
}

- (instancetype)initWithDictionary:(NSDictionary *)dictionary {
    self = [super init];
    if (self) {
        _primaryAccountIdentifier = [dictionary[@"primaryAccountIdentifier"] copy];
        _label = [dictionary[@"label"] copy];
        _assetName = [dictionary[@"assetName"] copy];
        _isAvailableForProvisioning = [dictionary[@"isAvailableForProvisioning"] boolValue];
        _cardholderName = [dictionary[@"cardholderName"] copy];
        _localizedDescription = [dictionary[@"localizedDescription"] copy];
        _primaryAccountSuffix = [dictionary[@"primaryAccountSuffix"] copy];
        _expiration = [dictionary[@"expiration"] copy];
    }
    return self;
}

- (NSDictionary *)toDictionary {
    return @{
        @"primaryAccountIdentifier": _primaryAccountIdentifier ?: @"",
        @"label": _label ?: @"",
        @"assetName": _assetName ?: @"",
        @"isAvailableForProvisioning": @(_isAvailableForProvisioning),
        @"cardholderName": _cardholderName ?: @"",
        @"localizedDescription": _localizedDescription ?: @"",
        @"primaryAccountSuffix": _primaryAccountSuffix ?: @"",
        @"expiration": _expiration ?: @""
    };
}

#pragma mark - NSCoding

- (instancetype)initWithCoder:(NSCoder *)coder {
    self = [super init];
    if (self) {
        _primaryAccountIdentifier = [coder decodeObjectOfClass:[NSString class] forKey:@"primaryAccountIdentifier"];
        _label = [coder decodeObjectOfClass:[NSString class] forKey:@"label"];
        _assetName = [coder decodeObjectOfClass:[NSString class] forKey:@"assetName"];
        _isAvailableForProvisioning = [coder decodeBoolForKey:@"isAvailableForProvisioning"];
        _cardholderName = [coder decodeObjectOfClass:[NSString class] forKey:@"cardholderName"];
        _localizedDescription = [coder decodeObjectOfClass:[NSString class] forKey:@"localizedDescription"];
        _primaryAccountSuffix = [coder decodeObjectOfClass:[NSString class] forKey:@"primaryAccountSuffix"];
        _expiration = [coder decodeObjectOfClass:[NSString class] forKey:@"expiration"];
    }
    return self;
}

- (void)encodeWithCoder:(NSCoder *)coder {
    [coder encodeObject:_primaryAccountIdentifier forKey:@"primaryAccountIdentifier"];
    [coder encodeObject:_label forKey:@"label"];
    [coder encodeObject:_assetName forKey:@"assetName"];
    [coder encodeBool:_isAvailableForProvisioning forKey:@"isAvailableForProvisioning"];
    [coder encodeObject:_cardholderName forKey:@"cardholderName"];
    [coder encodeObject:_localizedDescription forKey:@"localizedDescription"];
    [coder encodeObject:_primaryAccountSuffix forKey:@"primaryAccountSuffix"];
    [coder encodeObject:_expiration forKey:@"expiration"];
}

#pragma mark - NSCopying

- (id)copyWithZone:(NSZone *)zone {
    ProvisioningCredential *copy = [[[self class] allocWithZone:zone] init];
    if (copy) {
        copy->_primaryAccountIdentifier = [_primaryAccountIdentifier copyWithZone:zone];
        copy->_label = [_label copyWithZone:zone];
        copy->_assetName = [_assetName copyWithZone:zone];
        copy->_isAvailableForProvisioning = _isAvailableForProvisioning;
        copy->_cardholderName = [_cardholderName copyWithZone:zone];
        copy->_localizedDescription = [_localizedDescription copyWithZone:zone];
        copy->_primaryAccountSuffix = [_primaryAccountSuffix copyWithZone:zone];
        copy->_expiration = [_expiration copyWithZone:zone];
    }
    return copy;
}

#pragma mark - Equality

- (BOOL)isEqual:(id)object {
    if (self == object) return YES;
    // 修复：添加完整的类型检查条件
    if (![object isKindOfClass:[ProvisioningCredential class]]) return NO;
    
    ProvisioningCredential *other = (ProvisioningCredential *)object;
    return [self.primaryAccountIdentifier isEqual:other.primaryAccountIdentifier] &&
           [self.label isEqual:other.label] &&
           [self.assetName isEqual:other.assetName] &&
           self.isAvailableForProvisioning == other.isAvailableForProvisioning &&
           [self.cardholderName isEqual:other.cardholderName] &&
           [self.localizedDescription isEqual:other.localizedDescription] &&
           [self.primaryAccountSuffix isEqual:other.primaryAccountSuffix] &&
           [self.expiration isEqual:other.expiration];
}

- (NSUInteger)hash {
    return [self.primaryAccountIdentifier hash] ^
           [self.label hash] ^
           [self.assetName hash] ^
           [@(self.isAvailableForProvisioning) hash] ^
           [self.cardholderName hash] ^
           [self.localizedDescription hash] ^
           [self.primaryAccountSuffix hash] ^
           [self.expiration hash];
}

@end
