//
//  WatchConnectivitySession.h
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import <Foundation/Foundation.h>
#import <WatchConnectivity/WatchConnectivity.h>

NS_ASSUME_NONNULL_BEGIN

// 支持创建WCSession对象的类
@interface WatchConnectivitySession : NSObject <WCSessionDelegate>

@property (nonatomic, strong, readonly) WCSession *session;

// 当前iPhone是否已配对Apple Watch
@property (nonatomic, assign, readonly) BOOL isPaired;

- (instancetype)init NS_DESIGNATED_INITIALIZER;

@end

NS_ASSUME_NONNULL_END
