//
//  WatchConnectivitySession.m
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import "WatchConnectivitySession.h"

@implementation WatchConnectivitySession

- (instancetype)init {
    self = [super init];
    if (self) {
        _session = [WCSession defaultSession];
        
        // 如果当前iPhone可以使用会话对象，则激活会话
        if ([WCSession isSupported]) {
            _session.delegate = self;
            [_session activateSession];
        }
    }
    return self;
}

- (BOOL)isPaired {
    if (self.session.activationState == WCSessionActivationStateActivated) {
        return self.session.paired;
    } else {
        return NO;
    }
}

#pragma mark - WCSessionDelegate

- (void)session:(WCSession *)session activationDidCompleteWithState:(WCSessionActivationState)activationState error:(nullable NSError *)error {
    if (error) {
        NSLog(@"WCSession activation failed with error: %@", error.localizedDescription);
    }
}

- (void)sessionDidBecomeInactive:(WCSession *)session {
    // 会话变为非活动状态
}

- (void)sessionDidDeactivate:(WCSession *)session {
    // 重新激活会话
    [session activateSession];
}

// iOS特定方法（在Watch上不需要）
#if TARGET_OS_IOS
- (void)sessionWatchStateDidChange:(WCSession *)session {
    // Watch状态发生变化
}
#endif

@end
