//
//  ActionRequestHandler.h
//  IssuerApp
//
//  Created by Generated by Mark on 2026
//

#import <Foundation/Foundation.h>
#import <PassKit/PassKit.h>
#import "AppGroupShared.h"
#import "ProvisioningCredential.h"
#import "EncryptedPassDataResponse.h"
#import "PassResource.h"
#import "WatchConnectivitySession.h"

NS_ASSUME_NONNULL_BEGIN

// 非UI扩展的主类
@interface ActionRequestHandler : PKIssuerProvisioningExtensionHandler

@end

NS_ASSUME_NONNULL_END

